#!/bin/sh
# Refresh vendor/bochs/ — the Bochs CPU sources this crate compiles for its
# `bochs` backend.
#
#   usage:  sh scripts/vendor-bochs.sh
#
# You only need this to move to a different Bochs revision or to change the
# configure flags. A normal build compiles what is already in vendor/bochs/ and
# needs no network, no Bochs checkout and no autotools.
#
# What it does: clone stock Bochs at a pinned revision, run ./configure (whose
# only role is to generate config.h and bxversion.h), copy the curated subset
# that the CPU core needs, then apply patches/bochs/*.patch on top.
#
# Those patches are semantic fixes for upstream bugs this crate's differential
# suite found and upstream has not taken yet. They are applied HERE, not edited
# into vendor/bochs by hand, so that re-vendoring replays them instead of
# silently reverting them — the same discipline scripts/fix_cpp_model.py uses
# for the Sail model. A patch that stops applying is a hard error: it usually
# means upstream fixed the bug, in which case delete the patch (and say so in
# docs/backend-differences.md) rather than force it through.
#
# Requires: git, patch, a C++ compiler, make (for configure's probes). ~2 minutes.
set -eu

# Bochs 3.0.x. Pinned because csrc/bochs_shim.cpp calls CPU-internal APIs
# (cr0.set32(), read_eflags(), sregs[], vmm[]) that upstream occasionally
# renames, and because it builds a parameter tree that must cover every option
# the CPU core reads — a newly added one reads back NULL and segfaults. Bumping
# this is a code change, not a config change: expect to touch the shim.
BOCHS_REV=d5c0ad9f71397563b6c9f460e3e4679a08622a6e

CRATE=$(cd "$(dirname "$0")/.." && pwd)
DEST="$CRATE/vendor/bochs"
PATCHES="$CRATE/patches/bochs"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

echo ">> fetching Bochs $BOCHS_REV"
cd "$WORK"
git init -q repo
cd repo
git remote add origin https://github.com/bochs-emu/Bochs.git
git fetch -q --depth 1 origin "$BOCHS_REV"
git checkout -q FETCH_HEAD
cd bochs

echo ">> configuring (only to generate config.h / bxversion.h)"
# Keep these flags in sync with the comment in vendor/bochs/PROVENANCE.
CFLAGS="-O2 -fPIC" CXXFLAGS="-O2 -fPIC" ./configure \
    --enable-cpu-level=6 \
    --enable-x86-64 \
    --enable-avx \
    --enable-evex \
    --enable-cet \
    --enable-vmx=2 \
    --enable-pci \
    --enable-configurable-msrs \
    --enable-fast-function-calls \
    --enable-handlers-chaining \
    --disable-repeat-speedups \
    --disable-smp \
    --enable-instrumentation=instrument/stubs \
    --with-nogui \
    >configure.log 2>&1 || { tail -20 configure.log; exit 1; }

test -f config.h || { echo "configure did not produce config.h" >&2; exit 1; }

echo ">> copying sources into $DEST"
rm -rf "$DEST"
mkdir -p "$DEST"

# Every header, wherever it lives: they are small (~2.5 MB) and copying the lot
# avoids chasing transitive includes. host/ is platform-glue we never compile.
# *.def go too: Bochs builds its opcode and MSR tables with X-macros, so those
# files are #included like headers.
find . \( -name '*.h' -o -name '*.def' \) -not -path './host/*' | while read -r h; do
    mkdir -p "$DEST/$(dirname "$h")"
    cp "$h" "$DEST/$h"
done

# The translation units behind the five libraries the CPU core needs, plus the
# four emulator support files (logging, parameter tree, simulator interface,
# pc_system) that its code calls into. Bochs' config.cc is deliberately absent:
# it also initialises the plugin/device subsystems and aborts without them, so
# csrc/bochs_shim.cpp builds the small parameter tree the CPU actually reads.
for f in \
    cpu/*.cc \
    cpu/decoder/*.cc \
    cpu/fpu/*.cc \
    cpu/avx/*.cc \
    cpu/cpudb/*/*.cc \
    cpu/softfloat3e/*.cc \
    cpu/softfloat3e/8086-SSE/*.cc \
    logio.cc \
    pc_system.cc \
    gui/siminterface.cc \
    gui/paramtree.cc
do
    for src in $f; do
        [ -f "$src" ] || continue
        mkdir -p "$DEST/$(dirname "$src")"
        cp "$src" "$DEST/$src"
    done
done

cp COPYING LICENSE "$DEST/" 2>/dev/null || true

echo ">> applying $PATCHES"
applied=""
for p in "$PATCHES"/*.patch; do
    [ -f "$p" ] || continue
    name=$(basename "$p")
    patch -p1 -F0 --no-backup-if-mismatch -d "$DEST" -i "$p" || {
        echo "FAILED to apply $name — see the note in patches/bochs/ and in" >&2
        echo "docs/backend-differences.md before deciding to drop or rebase it." >&2
        exit 1
    }
    applied="$applied
           $name"
done
[ -n "$applied" ] || applied=" none"

cat > "$DEST/PROVENANCE" <<PROV
Bochs CPU sources, vendored for the hybrid-x86-oracle crate's \`bochs\` backend.

upstream:  https://github.com/bochs-emu/Bochs
revision:  $BOCHS_REV
retrieved: $(date -u +%Y-%m-%d)
patches:   applied from patches/bochs/ by scripts/vendor-bochs.sh:$applied

config.h and bxversion.h are generated by ./configure with:

  --enable-cpu-level=6 --enable-x86-64 --enable-avx --enable-evex --enable-cet
  --enable-vmx=2 --enable-pci --enable-configurable-msrs
  --enable-fast-function-calls --enable-handlers-chaining
  --disable-repeat-speedups --disable-smp
  --enable-instrumentation=instrument/stubs --with-nogui

Notes on those flags:
  --enable-avx/--enable-evex  the point of this backend is SIMD coverage
  --disable-smp               makes the CPU a process singleton, which
                              BochsOracle relies on
  --disable-repeat-speedups   keeps REP observable one iteration at a time
  --enable-instrumentation=instrument/stubs
                              uses Bochs' own stub headers, which only DECLARE
                              the bx_instr_* hooks; csrc/bochs_shim.cpp supplies
                              the bodies, and that is how a step stops after
                              exactly one instruction

config.h was generated on Linux, so it records that host's libc probe results.
build.rs rewrites the handful of lines that are wrong for an MSVC target (see
msvc_config_header there), so Windows needs nothing extra. For any other platform
whose answers differ, regenerate with this script there, or point BOCHS_DIR at
your own configured Bochs tree.

License: LGPL-2.1-or-later (see COPYING / LICENSE). Redistributed as source,
which is how this crate satisfies the LGPL for the statically linked result.

Regenerate with: sh scripts/vendor-bochs.sh
PROV

echo ">> done"
printf "    %s files, %s\n" \
    "$(find "$DEST" -type f | wc -l)" \
    "$(du -sh "$DEST" | cut -f1)"
echo "    now: cargo test --features bochs"
